Repository DarkOceanInteractive/project-wendigo, pull requests merged in 2022-03, with the labels that each got.

#3 feat: basic camera movements with mouse
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Scenes/Test Room.unity
  Assets/Scripts/Gameplay.meta
  Assets/Scripts/Gameplay/Player.meta
  Assets/Scripts/Gameplay/Player/CameraController.cs
  Assets/Scripts/Gameplay/Player/CameraController.cs.meta
Labels: feature

#5 ci: trigger build and publish release on tag push
  .github/workflows/main.yml
Labels: ci/build

#6 doc(license): add a license
  LICENSE
Labels: documentation
