Repository DarkOceanInteractive/project-wendigo, pull requests merged in 2022-04, with the labels that each got.

#17 feat: generic trigger box prefab
  Assets/Prefabs/Triggerbox.prefab
  Assets/Prefabs/Triggerbox.prefab.meta
  Assets/Scripts/Gameplay/TriggerBox.meta
  Assets/Scripts/Gameplay/TriggerBox/TriggerBox.cs
  Assets/Scripts/Gameplay/TriggerBox/TriggerBox.cs.meta
Labels: feature, priority: normal

#23 feat: add mine exit
  Assets/Scenes/Level1Mine.unity
Labels: feature

#24 feat: add FadeManager
  Assets/Animations.meta
  Assets/Animations/Fade_In.anim
  Assets/Animations/Fade_In.anim.meta
  Assets/Animations/Fade_Out.anim
  Assets/Animations/Fade_Out.anim.meta
  Assets/Animations/UI.controller
  Assets/Animations/UI.controller.meta
  Assets/Prefabs/Singletons.prefab
  Assets/Prefabs/UI.prefab
  Assets/Scenes/Level1Mine.unity
  Assets/Scripts/Inputs/PlayerControls.inputactions
  Assets/Scripts/Singletons/FadeManager.cs
  Assets/Scripts/Singletons/FadeManager.cs.meta
  Assets/Scripts/Singletons/InputManager.cs
  Assets/Scripts/Singletons/Singletons.cs
  Assets/TextMesh Pro/Examples & Extras/Scripts/SimpleScript.cs
Labels: feature

#25 fix: remove build obstacles
  Assets/Scripts/Common/Spline.cs
  Assets/TextMesh Pro/Examples & Extras/Scripts/TMP_TextInfoDebugTool.cs
  Assets/TextMesh Pro/Examples & Extras/Scripts/TMP_TextInfoDebugTool.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: ci/build

#26 tweak: disable sprinting, inventory and jumping
  Assets/Scripts/Singletons/InputManager.cs
Labels: enhancement
