Repository DarkOceanInteractive/project-wendigo, pull requests merged in 2022-06, with the labels that each got.

#56 hotfix: fix player gravity bug
  Assets/Scripts/Gameplay/Player/PlayerMovementStateContext.cs
Labels: bug

#57 feat(intro): gear and gun interactions and sounds
  Assets/Audio/Sounds/intro_phone_ringing.wav
  Assets/Audio/Sounds/intro_phone_ringing.wav.meta
  Assets/Audio/Sounds/intro_phone_static.wav
  Assets/Audio/Sounds/intro_phone_static.wav.meta
  Assets/Audio/Sounds/intro_phone_voice.wav
  Assets/Audio/Sounds/intro_phone_voice.wav.meta
  Assets/Audio/Sounds/intro_pickup_gear.wav
  Assets/Audio/Sounds/intro_pickup_gear.wav.meta
  Assets/Audio/Sounds/intro_pickup_gun.wav
  Assets/Audio/Sounds/intro_pickup_gun.wav.meta
  Assets/Scenes/IntroLevel.unity
  Assets/Scenes/Level2.unity
  Assets/Scripts/Common/Interact/Pickable.cs
Labels: feature

#58 feat: quest manager and intro level quest
  Assets/Prefabs/Singletons.prefab
  Assets/Scenes/IntroLevel.unity
  Assets/Scripts/Common/AStateContext.cs
  Assets/Scripts/Extensions/SetObjectInteractable.cs
  Assets/Scripts/Extensions/SetObjectInteractable.cs.meta
  Assets/Scripts/Gameplay/InteractableLoreItem.cs
  Assets/Scripts/Gameplay/Level0/CarKey.meta
  Assets/Scripts/Gameplay/Level0/CarKey/CarKeyInteraction.cs
  Assets/Scripts/Gameplay/Level0/CarKey/CarKeyInteraction.cs.meta
  Assets/Scripts/Gameplay/Level0/Events.meta
  Assets/Scripts/Gameplay/Level0/Events/DepartureEvent.cs
  Assets/Scripts/Gameplay/Level0/Events/DepartureEvent.cs.meta
  Assets/Scripts/Gameplay/Level0/Gear.meta
  Assets/Scripts/Gameplay/Level0/Gear/PickableGear.cs
  Assets/Scripts/Gameplay/Level0/Gear/PickableGear.cs.meta
  Assets/Scripts/Gameplay/Level0/Phone/PhoneStateContext.cs
  Assets/Scripts/Gameplay/Level0/Phone/PhoneStates/Calling.cs
  Assets/Scripts/Gameplay/Level0/Phone/PhoneStates/Idle.cs
  Assets/Scripts/Singletons/QuestManager.cs
  Assets/Scripts/Singletons/QuestManager.cs.meta
  Assets/Scripts/Singletons/Singletons.cs
Labels: feature

#62 fix: make brightness work in URP
  Assets/Art/PostProcessing/DarknessEffect.asset
  Assets/Scenes/IntroLevel.meta
  Assets/Scenes/IntroLevel.unity
  Assets/Scenes/IntroLevel/Camera Profile.asset
  Assets/Scenes/IntroLevel/Camera Profile.asset.meta
  Assets/Scripts/Scripts.asmdef
  Assets/Scripts/Singletons/OptionsManager.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
Labels: bug, priority: normal

#52 feat: church event
  Assets/Prefabs/Singletons.prefab
  Assets/Scripts/Gameplay/Level1/ChurchEvent.cs
  Assets/Scripts/Gameplay/Level1/ChurchEvent.cs.meta
  Assets/Scripts/Singletons/EventManager.cs
  Assets/Scripts/Singletons/EventManager.cs.meta
  Assets/Scripts/Singletons/Singletons.cs
Labels: feature

#63 feat: add ChangeSensitivity singleton method
  Assets/Scenes/IntroLevel.unity
  Assets/Scenes/Test Room.unity
  Assets/Scripts/Gameplay/Level1/ChurchEvent.cs
  Assets/Scripts/Gameplay/Level1/ChurchEvent/NearingBreathing.cs
  Assets/Scripts/Singletons/OptionsManager.cs
Labels: feature, priority: normal

#69 feat: add fade animations upon scene switch
  Assets/Prefabs/UI.prefab
  Assets/Scenes/Menu.unity
  Assets/Scripts/Singletons/FadeManager.cs
  Assets/Scripts/Singletons/SceneSwitcher.cs
  Assets/Scripts/UI/Menu/MainMenu.cs
Labels: enhancement, priority: low

#71 feat(mine): collect writings quest + journal entry
  Assets/Prefabs/EasterEggs/EasterEgg_Dwight.prefab
  Assets/Prefabs/EasterEggs/Materials.meta
  Assets/Prefabs/EasterEggs/Materials/EasterEgg_Dwight.mat
  Assets/Prefabs/EasterEggs/Materials/EasterEgg_Dwight.mat.meta
  Assets/Prefabs/PictureFrame/Textures/Dwight.png
  Assets/Prefabs/PictureFrame/Textures/Dwight.png.meta
  Assets/Prefabs/Trigger_EmptyBox_1.prefab
  Assets/Prefabs/UIElements/Notebook/Paging/Pages/LeftPage.prefab
  Assets/Prefabs/UIElements/Notebook/Paging/Pages/RightPage.prefab
  Assets/Scenes/IntroLevel.unity
  Assets/Scenes/Level2.unity
  Assets/Scenes/Menu.unity
  Assets/Scripts/Common/Interact/LoreInteract.cs
  Assets/Scripts/Extensions/LayerMaskContains.cs
  Assets/Scripts/Extensions/LayerMaskContains.cs.meta
  Assets/Scripts/Gameplay/Lantern/LanternInteraction.cs
  Assets/Scripts/Gameplay/Level0/Dwight/DwightInteraction.cs
  Assets/Scripts/Gameplay/LevelMine/Events.meta
  Assets/Scripts/Gameplay/LevelMine/Events/LanternEvent.cs
  Assets/Scripts/Gameplay/LevelMine/Events/LanternEvent.cs.meta
  Assets/Scripts/Gameplay/Notebook/Archive/Database/ArchiveCategoryTable.asset
  Assets/Scripts/Gameplay/Notebook/Archive/Database/ArchiveCollectionTable.asset
  Assets/Scripts/Gameplay/Notebook/Database/Collected/ANotebookCollectedTable.cs
  Assets/Scripts/Gameplay/Notebook/Journal/Adapter/JournalEntryAdapter.cs
  Assets/Scripts/Gameplay/Notebook/Journal/Database/JournalCollectionTable.asset
  Assets/Scripts/Gameplay/Notebook/NotebookSection.cs
  Assets/Scripts/Gameplay/Notebook/Paging/NotebookPaging.cs
  Assets/Scripts/Gameplay/TriggerBox/TriggerBox.cs
  Assets/Scripts/Singletons/NotebookManager.cs
Labels: bug, feature

#72 feat: polish outro
  Assets/Prefabs/Rocks/Rock1/Material/Rock1.mat
  Assets/Prefabs/Rocks/Rock2/Material/Rock2.mat
  Assets/Prefabs/Rocks/Rock3/Material/Rock3.mat
  Assets/Prefabs/Rocks/Rock4/Material/Rock4.mat
  Assets/Prefabs/Trees/Tree_Outro/Materials/Tree_Outro.mat
  Assets/Scenes/OutroLevel.unity
  Assets/Scripts/Gameplay/OutroLevel/SpawnFireEvent.cs
Labels: enhancement

#78 feat: add FlashlightEvent to level 2
  Assets/Animations/Flashlight.meta
  Assets/Animations/Flashlight/Drop.anim
  Assets/Animations/Flashlight/Drop.anim.meta
  Assets/Animations/Flashlight/Flashlight.controller
  Assets/Animations/Flashlight/Flashlight.controller.meta
  Assets/Scenes/Level2.unity
  Assets/Scripts/Gameplay/Equipables/LightingStateContext.cs
  Assets/Scripts/Gameplay/Equipables/LightingStates/Flickering.cs
  Assets/Scripts/Gameplay/LevelMine/Events/FlashlightEvent.cs
  Assets/Scripts/Gameplay/LevelMine/Events/FlashlightEvent.cs.meta
  Assets/Scripts/Gameplay/Notebook/Journal/Database/JournalCollectedTable.asset
Labels: feature, priority: high

#80 ci: run builds in development mode
  .github/workflows/main.yml
  Assets/Scenes/IntroLevel.unity
  Assets/Scripts/Editor/Editor.asmdef
  Assets/Scripts/Editor/Editor.asmdef.meta
  Assets/Scripts/Gameplay/Level0/CarKey/CarKeyInteraction.cs
  Assets/Scripts/Gameplay/Notebook/Archive/Database/ArchiveCollectedTable.asset
  Assets/Scripts/Scripts.asmdef
  Assets/Scripts/Singletons/NotebookManager.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: ci/build

#82 tweak: picture on family portrait prefab and archive entry
  Assets/Art/Textures/Archive/Family_Portrait.jpg
  Assets/Art/Textures/Archive/Family_Portrait.jpg.meta
  Assets/Prefabs/CarKey/CarKey.prefab
  Assets/Prefabs/PictureFrame/Materials/Picture2.mat
  Assets/Prefabs/PictureFrame/Materials/Picture2.mat.meta
  Assets/Prefabs/PictureFrame/Textures/ranger_family_portrait.jpg
  Assets/Prefabs/PictureFrame/Textures/ranger_family_portrait.jpg.meta
  Assets/Scenes/IntroLevel.unity
  Assets/Scripts/Gameplay/Notebook/Archive/Database/ArchiveCollectionTable.asset
Labels: enhancement

#85 feat: church event scene switch
  Assets/Prefabs/Daughter/Materials/Daughter_Ghost.mat
  Assets/Prefabs/Daughter/Materials/Daughter_Ghost.mat.meta
  Assets/Prefabs/Statues/Samodiva_Statue_Small/Statue_Samodiva_Small.prefab
  Assets/Scenes/Level1.unity
  Assets/Scripts/Gameplay/Level1/Events/ChurchEvent/ChurchEvent.cs
  Assets/Scripts/Gameplay/Level1/Events/ChurchEvent/ChurchEventInteractable.cs
  Assets/Scripts/Gameplay/Level1/Events/ChurchEvent/ChurchEventInteractable.cs.meta
Labels: feature

#86 feat: Added credits and auto-quit game
  Assets/Art/Textures/DarkOceanInteractiveLogo.png
  Assets/Art/Textures/DarkOceanInteractiveLogo.png.meta
  Assets/Scenes/OutroLevel.unity
  Assets/Scripts/Gameplay/OutroLevel/InteractableTriggerEnding.cs
Labels: feature

#88 feat and fix: multiple interactions in Intro and level 1 Scenes
  Assets/Art/Textures/Archive/miner_menifesto.png
  Assets/Art/Textures/Archive/miner_menifesto.png.meta
  Assets/Audio/Sounds/church_breathing.ogg
  Assets/Audio/Sounds/church_breathing.ogg.meta
  Assets/Audio/Sounds/truck_idle.mp3
  Assets/Audio/Sounds/truck_idle.mp3.meta
  Assets/Level1Terrain.asset
  Assets/Prefabs/Books/Book_Menifesto/Book_Menifesto.prefab
  Assets/Prefabs/Jeep/Truck.prefab
  Assets/Scenes/IntroLevel.unity
  Assets/Scenes/Level1.unity
  Assets/Scripts/Gameplay/Level0/Phone/PhoneInteraction.cs
  Assets/Scripts/Gameplay/Level1/Events/ChurchEvent/ChurchEventInteractable.cs
  Assets/Scripts/Gameplay/Notebook/Archive/Database/ArchiveCollectionTable.asset
  Assets/Scripts/Gameplay/Notebook/Journal/Database/JournalCollectionTable.asset
Labels: feature
